# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/winay/go/src/github.com/zennittians/mcl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/winay/go/src/github.com/zennittians/mcl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/winay/go/src/github.com/zennittians/mcl/CMakeFiles /home/winay/go/src/github.com/zennittians/mcl//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/winay/go/src/github.com/zennittians/mcl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mcl

# Build rule for target.
mcl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mcl
.PHONY : mcl

# fast build rule for target.
mcl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcl.dir/build.make CMakeFiles/mcl.dir/build
.PHONY : mcl/fast

#=============================================================================
# Target rules for targets named mcl_st

# Build rule for target.
mcl_st: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mcl_st
.PHONY : mcl_st

# fast build rule for target.
mcl_st/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcl_st.dir/build.make CMakeFiles/mcl_st.dir/build
.PHONY : mcl_st/fast

#=============================================================================
# Target rules for targets named mclbn256

# Build rule for target.
mclbn256: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mclbn256
.PHONY : mclbn256

# fast build rule for target.
mclbn256/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn256.dir/build.make CMakeFiles/mclbn256.dir/build
.PHONY : mclbn256/fast

#=============================================================================
# Target rules for targets named bn_c256_test

# Build rule for target.
bn_c256_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bn_c256_test
.PHONY : bn_c256_test

# fast build rule for target.
bn_c256_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bn_c256_test.dir/build.make CMakeFiles/bn_c256_test.dir/build
.PHONY : bn_c256_test/fast

#=============================================================================
# Target rules for targets named mclbn384

# Build rule for target.
mclbn384: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mclbn384
.PHONY : mclbn384

# fast build rule for target.
mclbn384/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn384.dir/build.make CMakeFiles/mclbn384.dir/build
.PHONY : mclbn384/fast

#=============================================================================
# Target rules for targets named bn_c384_test

# Build rule for target.
bn_c384_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bn_c384_test
.PHONY : bn_c384_test

# fast build rule for target.
bn_c384_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bn_c384_test.dir/build.make CMakeFiles/bn_c384_test.dir/build
.PHONY : bn_c384_test/fast

#=============================================================================
# Target rules for targets named mclbn384_256

# Build rule for target.
mclbn384_256: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mclbn384_256
.PHONY : mclbn384_256

# fast build rule for target.
mclbn384_256/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn384_256.dir/build.make CMakeFiles/mclbn384_256.dir/build
.PHONY : mclbn384_256/fast

#=============================================================================
# Target rules for targets named bn_c384_256_test

# Build rule for target.
bn_c384_256_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bn_c384_256_test
.PHONY : bn_c384_256_test

# fast build rule for target.
bn_c384_256_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bn_c384_256_test.dir/build.make CMakeFiles/bn_c384_256_test.dir/build
.PHONY : bn_c384_256_test/fast

#=============================================================================
# Target rules for targets named mclbn512

# Build rule for target.
mclbn512: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mclbn512
.PHONY : mclbn512

# fast build rule for target.
mclbn512/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn512.dir/build.make CMakeFiles/mclbn512.dir/build
.PHONY : mclbn512/fast

#=============================================================================
# Target rules for targets named bn_c512_test

# Build rule for target.
bn_c512_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bn_c512_test
.PHONY : bn_c512_test

# fast build rule for target.
bn_c512_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bn_c512_test.dir/build.make CMakeFiles/bn_c512_test.dir/build
.PHONY : bn_c512_test/fast

#=============================================================================
# Target rules for targets named fp_test

# Build rule for target.
fp_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fp_test
.PHONY : fp_test

# fast build rule for target.
fp_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fp_test.dir/build.make CMakeFiles/fp_test.dir/build
.PHONY : fp_test/fast

#=============================================================================
# Target rules for targets named ec_test

# Build rule for target.
ec_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ec_test
.PHONY : ec_test

# fast build rule for target.
ec_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ec_test.dir/build.make CMakeFiles/ec_test.dir/build
.PHONY : ec_test/fast

#=============================================================================
# Target rules for targets named fp_util_test

# Build rule for target.
fp_util_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fp_util_test
.PHONY : fp_util_test

# fast build rule for target.
fp_util_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fp_util_test.dir/build.make CMakeFiles/fp_util_test.dir/build
.PHONY : fp_util_test/fast

#=============================================================================
# Target rules for targets named window_method_test

# Build rule for target.
window_method_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 window_method_test
.PHONY : window_method_test

# fast build rule for target.
window_method_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/window_method_test.dir/build.make CMakeFiles/window_method_test.dir/build
.PHONY : window_method_test/fast

#=============================================================================
# Target rules for targets named elgamal_test

# Build rule for target.
elgamal_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 elgamal_test
.PHONY : elgamal_test

# fast build rule for target.
elgamal_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elgamal_test.dir/build.make CMakeFiles/elgamal_test.dir/build
.PHONY : elgamal_test/fast

#=============================================================================
# Target rules for targets named fp_tower_test

# Build rule for target.
fp_tower_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fp_tower_test
.PHONY : fp_tower_test

# fast build rule for target.
fp_tower_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fp_tower_test.dir/build.make CMakeFiles/fp_tower_test.dir/build
.PHONY : fp_tower_test/fast

#=============================================================================
# Target rules for targets named gmp_test

# Build rule for target.
gmp_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmp_test
.PHONY : gmp_test

# fast build rule for target.
gmp_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmp_test.dir/build.make CMakeFiles/gmp_test.dir/build
.PHONY : gmp_test/fast

#=============================================================================
# Target rules for targets named bn_test

# Build rule for target.
bn_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bn_test
.PHONY : bn_test

# fast build rule for target.
bn_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bn_test.dir/build.make CMakeFiles/bn_test.dir/build
.PHONY : bn_test/fast

#=============================================================================
# Target rules for targets named glv_test

# Build rule for target.
glv_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glv_test
.PHONY : glv_test

# fast build rule for target.
glv_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glv_test.dir/build.make CMakeFiles/glv_test.dir/build
.PHONY : glv_test/fast

src/asm/x86-64.bmi2.o: src/asm/x86-64.bmi2.s.o
.PHONY : src/asm/x86-64.bmi2.o

# target to build an object file
src/asm/x86-64.bmi2.s.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcl.dir/build.make CMakeFiles/mcl.dir/src/asm/x86-64.bmi2.s.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcl_st.dir/build.make CMakeFiles/mcl_st.dir/src/asm/x86-64.bmi2.s.o
.PHONY : src/asm/x86-64.bmi2.s.o

src/asm/x86-64.o: src/asm/x86-64.s.o
.PHONY : src/asm/x86-64.o

# target to build an object file
src/asm/x86-64.s.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcl.dir/build.make CMakeFiles/mcl.dir/src/asm/x86-64.s.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcl_st.dir/build.make CMakeFiles/mcl_st.dir/src/asm/x86-64.s.o
.PHONY : src/asm/x86-64.s.o

src/bn_c256.o: src/bn_c256.cpp.o
.PHONY : src/bn_c256.o

# target to build an object file
src/bn_c256.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn256.dir/build.make CMakeFiles/mclbn256.dir/src/bn_c256.cpp.o
.PHONY : src/bn_c256.cpp.o

src/bn_c256.i: src/bn_c256.cpp.i
.PHONY : src/bn_c256.i

# target to preprocess a source file
src/bn_c256.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn256.dir/build.make CMakeFiles/mclbn256.dir/src/bn_c256.cpp.i
.PHONY : src/bn_c256.cpp.i

src/bn_c256.s: src/bn_c256.cpp.s
.PHONY : src/bn_c256.s

# target to generate assembly for a file
src/bn_c256.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn256.dir/build.make CMakeFiles/mclbn256.dir/src/bn_c256.cpp.s
.PHONY : src/bn_c256.cpp.s

src/bn_c384.o: src/bn_c384.cpp.o
.PHONY : src/bn_c384.o

# target to build an object file
src/bn_c384.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn384.dir/build.make CMakeFiles/mclbn384.dir/src/bn_c384.cpp.o
.PHONY : src/bn_c384.cpp.o

src/bn_c384.i: src/bn_c384.cpp.i
.PHONY : src/bn_c384.i

# target to preprocess a source file
src/bn_c384.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn384.dir/build.make CMakeFiles/mclbn384.dir/src/bn_c384.cpp.i
.PHONY : src/bn_c384.cpp.i

src/bn_c384.s: src/bn_c384.cpp.s
.PHONY : src/bn_c384.s

# target to generate assembly for a file
src/bn_c384.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn384.dir/build.make CMakeFiles/mclbn384.dir/src/bn_c384.cpp.s
.PHONY : src/bn_c384.cpp.s

src/bn_c384_256.o: src/bn_c384_256.cpp.o
.PHONY : src/bn_c384_256.o

# target to build an object file
src/bn_c384_256.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn384_256.dir/build.make CMakeFiles/mclbn384_256.dir/src/bn_c384_256.cpp.o
.PHONY : src/bn_c384_256.cpp.o

src/bn_c384_256.i: src/bn_c384_256.cpp.i
.PHONY : src/bn_c384_256.i

# target to preprocess a source file
src/bn_c384_256.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn384_256.dir/build.make CMakeFiles/mclbn384_256.dir/src/bn_c384_256.cpp.i
.PHONY : src/bn_c384_256.cpp.i

src/bn_c384_256.s: src/bn_c384_256.cpp.s
.PHONY : src/bn_c384_256.s

# target to generate assembly for a file
src/bn_c384_256.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn384_256.dir/build.make CMakeFiles/mclbn384_256.dir/src/bn_c384_256.cpp.s
.PHONY : src/bn_c384_256.cpp.s

src/bn_c512.o: src/bn_c512.cpp.o
.PHONY : src/bn_c512.o

# target to build an object file
src/bn_c512.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn512.dir/build.make CMakeFiles/mclbn512.dir/src/bn_c512.cpp.o
.PHONY : src/bn_c512.cpp.o

src/bn_c512.i: src/bn_c512.cpp.i
.PHONY : src/bn_c512.i

# target to preprocess a source file
src/bn_c512.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn512.dir/build.make CMakeFiles/mclbn512.dir/src/bn_c512.cpp.i
.PHONY : src/bn_c512.cpp.i

src/bn_c512.s: src/bn_c512.cpp.s
.PHONY : src/bn_c512.s

# target to generate assembly for a file
src/bn_c512.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mclbn512.dir/build.make CMakeFiles/mclbn512.dir/src/bn_c512.cpp.s
.PHONY : src/bn_c512.cpp.s

src/fp.o: src/fp.cpp.o
.PHONY : src/fp.o

# target to build an object file
src/fp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcl.dir/build.make CMakeFiles/mcl.dir/src/fp.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcl_st.dir/build.make CMakeFiles/mcl_st.dir/src/fp.cpp.o
.PHONY : src/fp.cpp.o

src/fp.i: src/fp.cpp.i
.PHONY : src/fp.i

# target to preprocess a source file
src/fp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcl.dir/build.make CMakeFiles/mcl.dir/src/fp.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcl_st.dir/build.make CMakeFiles/mcl_st.dir/src/fp.cpp.i
.PHONY : src/fp.cpp.i

src/fp.s: src/fp.cpp.s
.PHONY : src/fp.s

# target to generate assembly for a file
src/fp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcl.dir/build.make CMakeFiles/mcl.dir/src/fp.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mcl_st.dir/build.make CMakeFiles/mcl_st.dir/src/fp.cpp.s
.PHONY : src/fp.cpp.s

test/bn_c256_test.o: test/bn_c256_test.cpp.o
.PHONY : test/bn_c256_test.o

# target to build an object file
test/bn_c256_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bn_c256_test.dir/build.make CMakeFiles/bn_c256_test.dir/test/bn_c256_test.cpp.o
.PHONY : test/bn_c256_test.cpp.o

test/bn_c256_test.i: test/bn_c256_test.cpp.i
.PHONY : test/bn_c256_test.i

# target to preprocess a source file
test/bn_c256_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bn_c256_test.dir/build.make CMakeFiles/bn_c256_test.dir/test/bn_c256_test.cpp.i
.PHONY : test/bn_c256_test.cpp.i

test/bn_c256_test.s: test/bn_c256_test.cpp.s
.PHONY : test/bn_c256_test.s

# target to generate assembly for a file
test/bn_c256_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bn_c256_test.dir/build.make CMakeFiles/bn_c256_test.dir/test/bn_c256_test.cpp.s
.PHONY : test/bn_c256_test.cpp.s

test/bn_c384_256_test.o: test/bn_c384_256_test.cpp.o
.PHONY : test/bn_c384_256_test.o

# target to build an object file
test/bn_c384_256_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bn_c384_256_test.dir/build.make CMakeFiles/bn_c384_256_test.dir/test/bn_c384_256_test.cpp.o
.PHONY : test/bn_c384_256_test.cpp.o

test/bn_c384_256_test.i: test/bn_c384_256_test.cpp.i
.PHONY : test/bn_c384_256_test.i

# target to preprocess a source file
test/bn_c384_256_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bn_c384_256_test.dir/build.make CMakeFiles/bn_c384_256_test.dir/test/bn_c384_256_test.cpp.i
.PHONY : test/bn_c384_256_test.cpp.i

test/bn_c384_256_test.s: test/bn_c384_256_test.cpp.s
.PHONY : test/bn_c384_256_test.s

# target to generate assembly for a file
test/bn_c384_256_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bn_c384_256_test.dir/build.make CMakeFiles/bn_c384_256_test.dir/test/bn_c384_256_test.cpp.s
.PHONY : test/bn_c384_256_test.cpp.s

test/bn_c384_test.o: test/bn_c384_test.cpp.o
.PHONY : test/bn_c384_test.o

# target to build an object file
test/bn_c384_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bn_c384_test.dir/build.make CMakeFiles/bn_c384_test.dir/test/bn_c384_test.cpp.o
.PHONY : test/bn_c384_test.cpp.o

test/bn_c384_test.i: test/bn_c384_test.cpp.i
.PHONY : test/bn_c384_test.i

# target to preprocess a source file
test/bn_c384_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bn_c384_test.dir/build.make CMakeFiles/bn_c384_test.dir/test/bn_c384_test.cpp.i
.PHONY : test/bn_c384_test.cpp.i

test/bn_c384_test.s: test/bn_c384_test.cpp.s
.PHONY : test/bn_c384_test.s

# target to generate assembly for a file
test/bn_c384_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bn_c384_test.dir/build.make CMakeFiles/bn_c384_test.dir/test/bn_c384_test.cpp.s
.PHONY : test/bn_c384_test.cpp.s

test/bn_c512_test.o: test/bn_c512_test.cpp.o
.PHONY : test/bn_c512_test.o

# target to build an object file
test/bn_c512_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bn_c512_test.dir/build.make CMakeFiles/bn_c512_test.dir/test/bn_c512_test.cpp.o
.PHONY : test/bn_c512_test.cpp.o

test/bn_c512_test.i: test/bn_c512_test.cpp.i
.PHONY : test/bn_c512_test.i

# target to preprocess a source file
test/bn_c512_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bn_c512_test.dir/build.make CMakeFiles/bn_c512_test.dir/test/bn_c512_test.cpp.i
.PHONY : test/bn_c512_test.cpp.i

test/bn_c512_test.s: test/bn_c512_test.cpp.s
.PHONY : test/bn_c512_test.s

# target to generate assembly for a file
test/bn_c512_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bn_c512_test.dir/build.make CMakeFiles/bn_c512_test.dir/test/bn_c512_test.cpp.s
.PHONY : test/bn_c512_test.cpp.s

test/bn_test.o: test/bn_test.cpp.o
.PHONY : test/bn_test.o

# target to build an object file
test/bn_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bn_test.dir/build.make CMakeFiles/bn_test.dir/test/bn_test.cpp.o
.PHONY : test/bn_test.cpp.o

test/bn_test.i: test/bn_test.cpp.i
.PHONY : test/bn_test.i

# target to preprocess a source file
test/bn_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bn_test.dir/build.make CMakeFiles/bn_test.dir/test/bn_test.cpp.i
.PHONY : test/bn_test.cpp.i

test/bn_test.s: test/bn_test.cpp.s
.PHONY : test/bn_test.s

# target to generate assembly for a file
test/bn_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bn_test.dir/build.make CMakeFiles/bn_test.dir/test/bn_test.cpp.s
.PHONY : test/bn_test.cpp.s

test/ec_test.o: test/ec_test.cpp.o
.PHONY : test/ec_test.o

# target to build an object file
test/ec_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ec_test.dir/build.make CMakeFiles/ec_test.dir/test/ec_test.cpp.o
.PHONY : test/ec_test.cpp.o

test/ec_test.i: test/ec_test.cpp.i
.PHONY : test/ec_test.i

# target to preprocess a source file
test/ec_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ec_test.dir/build.make CMakeFiles/ec_test.dir/test/ec_test.cpp.i
.PHONY : test/ec_test.cpp.i

test/ec_test.s: test/ec_test.cpp.s
.PHONY : test/ec_test.s

# target to generate assembly for a file
test/ec_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ec_test.dir/build.make CMakeFiles/ec_test.dir/test/ec_test.cpp.s
.PHONY : test/ec_test.cpp.s

test/elgamal_test.o: test/elgamal_test.cpp.o
.PHONY : test/elgamal_test.o

# target to build an object file
test/elgamal_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elgamal_test.dir/build.make CMakeFiles/elgamal_test.dir/test/elgamal_test.cpp.o
.PHONY : test/elgamal_test.cpp.o

test/elgamal_test.i: test/elgamal_test.cpp.i
.PHONY : test/elgamal_test.i

# target to preprocess a source file
test/elgamal_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elgamal_test.dir/build.make CMakeFiles/elgamal_test.dir/test/elgamal_test.cpp.i
.PHONY : test/elgamal_test.cpp.i

test/elgamal_test.s: test/elgamal_test.cpp.s
.PHONY : test/elgamal_test.s

# target to generate assembly for a file
test/elgamal_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elgamal_test.dir/build.make CMakeFiles/elgamal_test.dir/test/elgamal_test.cpp.s
.PHONY : test/elgamal_test.cpp.s

test/fp_test.o: test/fp_test.cpp.o
.PHONY : test/fp_test.o

# target to build an object file
test/fp_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fp_test.dir/build.make CMakeFiles/fp_test.dir/test/fp_test.cpp.o
.PHONY : test/fp_test.cpp.o

test/fp_test.i: test/fp_test.cpp.i
.PHONY : test/fp_test.i

# target to preprocess a source file
test/fp_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fp_test.dir/build.make CMakeFiles/fp_test.dir/test/fp_test.cpp.i
.PHONY : test/fp_test.cpp.i

test/fp_test.s: test/fp_test.cpp.s
.PHONY : test/fp_test.s

# target to generate assembly for a file
test/fp_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fp_test.dir/build.make CMakeFiles/fp_test.dir/test/fp_test.cpp.s
.PHONY : test/fp_test.cpp.s

test/fp_tower_test.o: test/fp_tower_test.cpp.o
.PHONY : test/fp_tower_test.o

# target to build an object file
test/fp_tower_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fp_tower_test.dir/build.make CMakeFiles/fp_tower_test.dir/test/fp_tower_test.cpp.o
.PHONY : test/fp_tower_test.cpp.o

test/fp_tower_test.i: test/fp_tower_test.cpp.i
.PHONY : test/fp_tower_test.i

# target to preprocess a source file
test/fp_tower_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fp_tower_test.dir/build.make CMakeFiles/fp_tower_test.dir/test/fp_tower_test.cpp.i
.PHONY : test/fp_tower_test.cpp.i

test/fp_tower_test.s: test/fp_tower_test.cpp.s
.PHONY : test/fp_tower_test.s

# target to generate assembly for a file
test/fp_tower_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fp_tower_test.dir/build.make CMakeFiles/fp_tower_test.dir/test/fp_tower_test.cpp.s
.PHONY : test/fp_tower_test.cpp.s

test/fp_util_test.o: test/fp_util_test.cpp.o
.PHONY : test/fp_util_test.o

# target to build an object file
test/fp_util_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fp_util_test.dir/build.make CMakeFiles/fp_util_test.dir/test/fp_util_test.cpp.o
.PHONY : test/fp_util_test.cpp.o

test/fp_util_test.i: test/fp_util_test.cpp.i
.PHONY : test/fp_util_test.i

# target to preprocess a source file
test/fp_util_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fp_util_test.dir/build.make CMakeFiles/fp_util_test.dir/test/fp_util_test.cpp.i
.PHONY : test/fp_util_test.cpp.i

test/fp_util_test.s: test/fp_util_test.cpp.s
.PHONY : test/fp_util_test.s

# target to generate assembly for a file
test/fp_util_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fp_util_test.dir/build.make CMakeFiles/fp_util_test.dir/test/fp_util_test.cpp.s
.PHONY : test/fp_util_test.cpp.s

test/glv_test.o: test/glv_test.cpp.o
.PHONY : test/glv_test.o

# target to build an object file
test/glv_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glv_test.dir/build.make CMakeFiles/glv_test.dir/test/glv_test.cpp.o
.PHONY : test/glv_test.cpp.o

test/glv_test.i: test/glv_test.cpp.i
.PHONY : test/glv_test.i

# target to preprocess a source file
test/glv_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glv_test.dir/build.make CMakeFiles/glv_test.dir/test/glv_test.cpp.i
.PHONY : test/glv_test.cpp.i

test/glv_test.s: test/glv_test.cpp.s
.PHONY : test/glv_test.s

# target to generate assembly for a file
test/glv_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glv_test.dir/build.make CMakeFiles/glv_test.dir/test/glv_test.cpp.s
.PHONY : test/glv_test.cpp.s

test/gmp_test.o: test/gmp_test.cpp.o
.PHONY : test/gmp_test.o

# target to build an object file
test/gmp_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmp_test.dir/build.make CMakeFiles/gmp_test.dir/test/gmp_test.cpp.o
.PHONY : test/gmp_test.cpp.o

test/gmp_test.i: test/gmp_test.cpp.i
.PHONY : test/gmp_test.i

# target to preprocess a source file
test/gmp_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmp_test.dir/build.make CMakeFiles/gmp_test.dir/test/gmp_test.cpp.i
.PHONY : test/gmp_test.cpp.i

test/gmp_test.s: test/gmp_test.cpp.s
.PHONY : test/gmp_test.s

# target to generate assembly for a file
test/gmp_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmp_test.dir/build.make CMakeFiles/gmp_test.dir/test/gmp_test.cpp.s
.PHONY : test/gmp_test.cpp.s

test/window_method_test.o: test/window_method_test.cpp.o
.PHONY : test/window_method_test.o

# target to build an object file
test/window_method_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/window_method_test.dir/build.make CMakeFiles/window_method_test.dir/test/window_method_test.cpp.o
.PHONY : test/window_method_test.cpp.o

test/window_method_test.i: test/window_method_test.cpp.i
.PHONY : test/window_method_test.i

# target to preprocess a source file
test/window_method_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/window_method_test.dir/build.make CMakeFiles/window_method_test.dir/test/window_method_test.cpp.i
.PHONY : test/window_method_test.cpp.i

test/window_method_test.s: test/window_method_test.cpp.s
.PHONY : test/window_method_test.s

# target to generate assembly for a file
test/window_method_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/window_method_test.dir/build.make CMakeFiles/window_method_test.dir/test/window_method_test.cpp.s
.PHONY : test/window_method_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... bn_c256_test"
	@echo "... bn_c384_256_test"
	@echo "... bn_c384_test"
	@echo "... bn_c512_test"
	@echo "... bn_test"
	@echo "... ec_test"
	@echo "... elgamal_test"
	@echo "... fp_test"
	@echo "... fp_tower_test"
	@echo "... fp_util_test"
	@echo "... glv_test"
	@echo "... gmp_test"
	@echo "... mcl"
	@echo "... mcl_st"
	@echo "... mclbn256"
	@echo "... mclbn384"
	@echo "... mclbn384_256"
	@echo "... mclbn512"
	@echo "... window_method_test"
	@echo "... src/asm/x86-64.bmi2.o"
	@echo "... src/asm/x86-64.o"
	@echo "... src/bn_c256.o"
	@echo "... src/bn_c256.i"
	@echo "... src/bn_c256.s"
	@echo "... src/bn_c384.o"
	@echo "... src/bn_c384.i"
	@echo "... src/bn_c384.s"
	@echo "... src/bn_c384_256.o"
	@echo "... src/bn_c384_256.i"
	@echo "... src/bn_c384_256.s"
	@echo "... src/bn_c512.o"
	@echo "... src/bn_c512.i"
	@echo "... src/bn_c512.s"
	@echo "... src/fp.o"
	@echo "... src/fp.i"
	@echo "... src/fp.s"
	@echo "... test/bn_c256_test.o"
	@echo "... test/bn_c256_test.i"
	@echo "... test/bn_c256_test.s"
	@echo "... test/bn_c384_256_test.o"
	@echo "... test/bn_c384_256_test.i"
	@echo "... test/bn_c384_256_test.s"
	@echo "... test/bn_c384_test.o"
	@echo "... test/bn_c384_test.i"
	@echo "... test/bn_c384_test.s"
	@echo "... test/bn_c512_test.o"
	@echo "... test/bn_c512_test.i"
	@echo "... test/bn_c512_test.s"
	@echo "... test/bn_test.o"
	@echo "... test/bn_test.i"
	@echo "... test/bn_test.s"
	@echo "... test/ec_test.o"
	@echo "... test/ec_test.i"
	@echo "... test/ec_test.s"
	@echo "... test/elgamal_test.o"
	@echo "... test/elgamal_test.i"
	@echo "... test/elgamal_test.s"
	@echo "... test/fp_test.o"
	@echo "... test/fp_test.i"
	@echo "... test/fp_test.s"
	@echo "... test/fp_tower_test.o"
	@echo "... test/fp_tower_test.i"
	@echo "... test/fp_tower_test.s"
	@echo "... test/fp_util_test.o"
	@echo "... test/fp_util_test.i"
	@echo "... test/fp_util_test.s"
	@echo "... test/glv_test.o"
	@echo "... test/glv_test.i"
	@echo "... test/glv_test.s"
	@echo "... test/gmp_test.o"
	@echo "... test/gmp_test.i"
	@echo "... test/gmp_test.s"
	@echo "... test/window_method_test.o"
	@echo "... test/window_method_test.i"
	@echo "... test/window_method_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

